services:
  kicks-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${APPLICATION__PORT}:${APPLICATION__PORT}"
    environment:
      APPLICATION__PRETTY_LOG: false
      APPLICATION__LOG_LEVEL: debug
      DATABASE__HOST: kicks-postgres
      DATABASE__PORT: 5432
      DATABASE_URL: postgres://${DATABASE__USER}:${DATABASE__PASSWORD}@kicks-postgres:5432/${DATABASE__NAME}
      REDIS__HOST: kicks-redis
      REDIS__PORT: 6379
    depends_on:
      kicks-postgres:
        condition: service_healthy
      kicks-redis:
        condition: service_healthy

  kicks-postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_DB: ${DATABASE__NAME}
    volumes:
      - kicks-postgres-data:/var/lib/postgresql
    ports:
      - "${DATABASE__PORT}:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE__USER} -d ${DATABASE__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  kicks-redis:
    image: redis:8-alpine
    restart: always
    command: redis-server --requirepass ${REDIS__PASSWORD}
    volumes:
      - kicks-redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS__PASSWORD} ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "${REDIS__PORT}:6379"

volumes:
  kicks-postgres-data:
  kicks-redis-data:
