application:
  port: 4000
  host: 127.0.0.1
  client_url: http://localhost:5173
  account_verification_path: /auth/account-verification
  reset_password_path: /auth/reset-password
  session_cookie_name: somename
  oauth_state_cookie_name: somestatename
  cookie_secure: true
  cookie_secret: d70934657c0a6630711177bf7a11b2d06d505e645aafd492aa8b687284c480d3527e3e38c4ff86d53667738aa861edb10496
  account_verification_ttl_minutes: 1440
  session_ttl_minutes: 43200
  oauth_state_ttl_minutes: 3
  reset_password_ttl_minutes: 10
  log_level: info
  pretty_log: true

database:
  host: localhost
  port: 5432
  name: kicks
  user: postgres
  password: password
  ssl: false

redis:
  host: localhost
  port: 6379
  user: ""
  password: ""
  database: 0

oauth2:
  google_redirect_url: http://localhost:4000/api/v1/auth/google/callback
  facebook_redirect_url: http://localhost:4000/api/v1/auth/facebook/callback

ratelimit:
  sign_up: 10
  sign_in: 10
  verify_account: 10
  get_me: 20
  forgot_password: 5
  reset_password: 5
  logout: 5
