name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.6
  SQLX_FEATURES: "native-tls,postgres"
  APP_DB_NAME: kicks
  APPLICATION__ENV: test-ci
  SMTP__HOST: ${{ secrets.SMTP__HOST }}
  SMTP__PORT: ${{ secrets.SMTP__PORT }}
  SMTP__USER: ${{ secrets.SMTP__USER }}
  SMTP__PASSWORD: ${{ secrets.SMTP__PASSWORD }}
  SMTP__FROM: ${{ secrets.SMTP__FROM }}

  CLOUDINARY__API_KEY: ${{ secrets.CLOUDINARY__API_KEY }}
  CLOUDINARY__SECRET: ${{ secrets.CLOUDINARY__SECRET }}
  CLOUDINARY__CLOUD_NAME: ${{ secrets.CLOUDINARY__CLOUD_NAME }}
  CLOUDINARY__FOLDER: ${{ secrets.CLOUDINARY__FOLDER }}

  OAUTH2__GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2__GOOGLE_CLIENT_ID }}
  OAUTH2__GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2__GOOGLE_CLIENT_SECRET }}
  OAUTH2__FACEBOOK_CLIENT_ID: ${{ secrets.OAUTH2__FACEBOOK_CLIENT_ID }}
  OAUTH2__FACEBOOK_CLIENT_SECRET: ${{ secrets.OAUTH2__FACEBOOK_CLIENT_SECRET }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ${{ env.APP_DB_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli \
            --version=${{ env.SQLX_VERSION }} \
            --features ${{ env.SQLX_FEATURES }} \
            --no-default-features \
            --locked

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run tests
        run: cargo test --workspace --all-targets

      - name: Check that queries are fresh
        run: cargo sqlx prepare --workspace --check -- --all-targets

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Enforce formatting
        run: cargo fmt --check --all

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain with clippy
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Linting
        run: cargo clippy --workspace --all-targets -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain with llvm-tools
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli \
            --version=${{ env.SQLX_VERSION }} \
            --features ${{ env.SQLX_FEATURES }} \
            --no-default-features \
            --locked

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Migrate database
        run: SKIP_DOCKER=true DATABASE_NAME=${{ env.APP_DB_NAME }} ./scripts/init_db.sh

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Generate HTML report
        run: cargo llvm-cov report --html --output-dir coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Coverage report
          path: coverage/
